theme: jekyll-theme-cayman
title: MobiFace
description: A Novel Dataset for Mobile Face Tracking and Face Grouping in the Wild
arxiv:
  show_arxiv: true
  paper_url: https://arxiv.org/abs/1805.09749v2
google_analytics: UA-132987889-1
tool_url: https://drive.google.com/open?id=12P6s3ipa1VuLJcRakV0E-pXMI6p7Xo0f
